os: Visual Studio 2015

platform: x64

install:
  # Install rakudostar for faster CI builds.
  - choco install rakudostar
  # For Base64::Native
  - choco install make
  - choco install mingw
  # Change to build folder
  - cd %APPVEYOR_BUILD_FOLDER%
  # Refresh environment variables so zef works
  - refreshenv

build: off

test_script:
  # spoon-feed deps for older zef versions
  - zef install PDF::Grammar
  - zef install PDF
  - zef install PDF::Content
  - zef install Base64::Native
  - zef install Native::Packing
  - zef install Compress::Zlib::Raw
  - zef --deps-only install .
  - prove -ve "perl6 -I."
  - zef install .

shallow_clone: true
